### ISSUE TITLE
Missing ARM version in debug

### ISSUE THREAD

**Issue by renewest** [vortex314/serial2mqtt#1]
Hi,

Can you please upload a compiled  version for ARM? 

Thanks.

**Comment by vortex314** [comment]
Hi, I've uploaded the PI3 compiled version. Not sure about the backwards compatibility with a PI1 version.
Let me know how it goes.
Regards

**Comment by vortex314** [comment]
Contains now armv6l ( Raspberry Pi -1) and armv7l ( PI 3 ) in binaruy version in Debug directory. 
I permission denies occurs on /dev/ttyUSB0 , then execute : sudo usermod -a -G dialout $USER

**Comment by renewest** [comment]
Hi,

Thank you. Working great on a orange pi zero (arm7)!

Regards

Op za 9 feb. 2019 09:48 schreef Lieven <notifications@github.com:
