### ISSUE TITLE
Ignoring serial2mqtt JSON file

### ISSUE THREAD

**Issue by banier1** [vortex314/serial2mqtt#16]
Hi Lieven,

Hope you are well.  I'm having another go at using your code for my setup.
With some help, I've tried a number of times with different settings and have come to notice that the serial2mqtt.json seems to be being ignored.  I've changed the items in this file a number of time with the output not changing.
I have been using -m and -f on the command line to get basic functionality but need to use the different USB serial interface.

See example in attached screen shots, using the following command:
"./serial2mqtt.armv7l -f serial2mqtt.json -m 192.168.1.117"

![Screen Shot 2020-12-13 at 13 57 18](https://user-images.githubusercontent.com/66334240/102014390-98c8ba80-3d4d-11eb-98c5-a818bb222c7e.png)
![Screen Shot 2020-12-13 at 13 56 41](https://user-images.githubusercontent.com/66334240/102014392-9b2b1480-3d4d-11eb-8814-61405a9d3645.png)

**Comment by vortex314** [comment]
Hi ,
thanks for getting my attention on this issue. I guess you started from the build in the build directory, as this was not updated recently it still contained an old bug, can you do a git pull and try again ?

Thanks,
Lieven

**Comment by banier1** [comment]
So can you confirm that the recent updates are included in the build when executing the previously prescribed commands?, namely:
+   curl -O https://raw.githubusercontent.com/vortex314/serial2mqtt/master/build/serial2mqtt.armv7l.zip
+   unzip serial2mqtt.armv7l.zip
+   cd Debug
+   curl -O https://raw.githubusercontent.com/vortex314/serial2mqtt/master/serial2mqtt.json
+   ./serial2mqtt.armv7l

**Comment by vortex314** [comment]
Yes, should work. Just tested it and changes are accepted. See also start of log that shows if config has been accepted.

**Comment by vortex314** [comment]
Any feedback ? @banier1

**Comment by PizzaProgram** [comment]
IMHO the 136. Line at:
https://github.com/vortex314/serial2mqtt/blob/master/Serial2Mqtt.cpp

Should be changed to:
```
_config.get("connection", _mqttConnection, "tcp://localhost:1883");
```
instead of "tcp://test.mosquitto.org:1883" too.
It seems to me more logical to have "localhost" as default.

**Comment by banier1** [comment]
> Any feedback ? @banier1

Yes - it worked.  Seems a shame that recent updates were not included in this build process.

I also notice that there have been further updates in the past week or so.  (colour coding!?) Would these updates be included if I went through the build process again?

Thanks, Dan

**Comment by vortex314** [comment]
Hi Dan, if you update the code locally and compile again, the features should be included. I'll make a ready for use zip file also for raspberry.

**Comment by banier1** [comment]
Hi Lieven,

Did you make the updates so I can use the following command to up-revision the RPI module?

- curl -O https://raw.githubusercontent.com/vortex314/serial2mqtt/master/build/serial2mqtt.armv7l.zip
- unzip serial2mqtt.armv7l.zip
- cd Debug
- curl -O https://raw.githubusercontent.com/vortex314/serial2mqtt/master/serial2mqtt.json
- ./serial2mqtt.armv7l

**Comment by vortex314** [comment]
Yes,I did.just check json config for the right broker. Looks it's still pointing to my server.

**Comment by banier1** [comment]
Something is not right with this updated version.  Could you provide a link to the previous version? (the one I downloaded 19 days ago)

**Comment by vortex314** [comment]
You can elaborate on what you see as an issue ? As this version is running for a few days now on a raspberry with me. 
Older version can be retrieved through github : https://github.com/vortex314/serial2mqtt/commits/master/build

**Comment by banier1** [comment]
![Screen Shot 2021-01-03 at 13 28 47](https://user-images.githubusercontent.com/66334240/103479842-59c7db00-4dc8-11eb-829d-2cc7c52dca9e.png)

It seems to be truncating the Topic ID.  see screenshot

**Comment by banier1** [comment]
Hi Lieven,  Did you find the issues with the problem i have been experiencing?

Regards, Dan

**Comment by vortex314** [comment]
Looking at the line in blue, got the impression that the Arduino code is generating invalid JSON. 
There are 2 colons in that string, as it is not parsed correctly by serial2mqtt, it displays this as debug output in blue.
Are you handcrafting the JSON in Arduino or using ArduinoJson ?

**Comment by PizzaProgram** [comment]
@banier1 Hi,
 Can you please share your Arduino .ino file?
It would be great to see, how you did it.
 Thanks :+1: 

PS.: I'm thinking on creating a "standard" sketch file, that could be used globally on all Nanos.
+ Enhancing it with better serial com. (Event bit + flow control)
+ maybe making a Node-RED receiver for it.
+ give CRC32 or SHA
+ give security ?

**Comment by vortex314** [comment]
Good idea, there is also an attention point on serial buffer size which would be good to add, I've seen on some Arduino's you can increase that. 
https://www.hobbytronics.co.uk/arduino-serial-buffer-size

**Comment by halfbakery** [comment]
No need to mod anymore, newer arduino SDK-s contains the following code in HardwareSerial.h:
```
#if !defined(SERIAL_TX_BUFFER_SIZE)
#if ((RAMEND - RAMSTART) < 1023)
#define SERIAL_TX_BUFFER_SIZE 16
#else
#define SERIAL_TX_BUFFER_SIZE 64
#endif
#endif
#if !defined(SERIAL_RX_BUFFER_SIZE)
#if ((RAMEND - RAMSTART) < 1023)
#define SERIAL_RX_BUFFER_SIZE 16
#else
#define SERIAL_RX_BUFFER_SIZE 64
#endif
#endif
```

So just add a define to the command line (untested, but should work)

**Comment by halfbakery** [comment]
I have a similar problem, so I started to investigate. It seems this is some early buffered data related to opening USB serial ports:
https://stackoverflow.com/questions/13013387/clearing-the-serial-ports-buffer

It affects just the opening phase, no problems after. I'll try to figure out something (e.g. dropping data in the first t millisec).

**Comment by halfbakery** [comment]
> No need to mod anymore, newer arduino SDK-s contains the following code in HardwareSerial.h:
> 
> ```
> #if !defined(SERIAL_TX_BUFFER_SIZE)
> #if ((RAMEND - RAMSTART) < 1023)
> #define SERIAL_TX_BUFFER_SIZE 16
> #else
> #define SERIAL_TX_BUFFER_SIZE 64
> #endif
> #endif
> #if !defined(SERIAL_RX_BUFFER_SIZE)
> #if ((RAMEND - RAMSTART) < 1023)
> #define SERIAL_RX_BUFFER_SIZE 16
> #else
> #define SERIAL_RX_BUFFER_SIZE 64
> #endif
> #endif
> ```
> 
> So just add a define to the command line (untested, but should work)

I tested it some days ago and it works like a charm.

**Comment by vortex314** [comment]
No more feedback received from banier1.

**Comment by banier1** [comment]
> @banier1 Hi,
> Can you please share your Arduino .ino file?
> It would be great to see, how you did it.
> Thanks 👍
> 
> PS.: I'm thinking on creating a "standard" sketch file, that could be used globally on all Nanos.
> 
> * Enhancing it with better serial com. (Event bit + flow control)
> * maybe making a Node-RED receiver for it.
> * give CRC32 or SHA
> * give security ?

https://github.com/ncmreynolds/serial2mqtt

**Comment by vortex314** [comment]
@banier1 the github repository mentioned is private or does not exist.

**Comment by banier1** [comment]
https://www.facebook.com/groups/raspberrypint/permalink/4436611866352297/

**Comment by vortex314** [comment]
Nice ! Thanks for the feedback!

**Comment by banier1** [comment]
https://github.com/ncmreynolds/serial2mqtt

**Comment by vortex314** [comment]
Nicely done and presented !
