### ISSUE TITLE
Extra instructions?

### ISSUE THREAD

**Issue by jc508** [vortex314/serial2mqtt#2]
Lieven, sorry to be a pain but I am new to all this.
From your readme this is exactly what I need to get my RPi3 talking to my Arduino. 
The Raspberry is running Mosquito which has been started as a service.
I have followed your instructions to get and unzip the pre-built version of serial2mqtt

However I think I need some more instructions please to get this connected.
1. How exactly do I run 'serial2mqtt' ? and does it or should it run as service at startup ?
2. How is this configured to a) use mosquitto and b) to specify the port etc that the arduino will connect to
Thanks
JC

**Comment by jc508** [comment]
I can answer part of this my self now.  The "programmer":  section of the serial2mqtt.json can be eliminated if not using that functionality.

**Comment by vortex314** [comment]
Hi JC,
at this stage you can just run the serial2mqtt from the  command line. I guess it should be easy to run it as a service. See : https://bash.cyberciti.biz/guide/Service_command . I didn't try this myself yet.

The mosquitto server can be configured in the serial2mqtt.json , as you run it locally you can specify 'localhost'.

The serial ports are also there specified. Example : https://github.com/vortex314/serial2mqtt/blob/master/serial2mqtt.json
Depending on the USB to serial chip attached the the name can change : /dev/ttyACMx or /dev/ttyUSBx. 

As I'm working most of the time with ESP32 and ESP8266 , I didn't want to stop&start the serial2mqtt everytime again. SO the idea was to download the ESPxxx image via mqtt and the download this through the commandline : 'esptool'.
Hope this helps,
Lieven
