### ISSUE TITLE
compilation issue on raspberry pi

### ISSUE THREAD

**Issue by vortex314** [vortex314/serial2mqtt#20]
```
ieven@pi30:~/workspace/serial2mqtt $ make -f serial2mqtt.mk
/usr/bin/g++  -c  "Serial2Mqtt.cpp" -g -O0 -Wall -std=c++0x  -o ./Debug/Serial2Mqtt.cpp.o -I. -I. -I../Common -I../ArduinoJson/src -I../paho.mqtt.c/src 
In file included from /usr/include/c++/8/bits/stl_algobase.h:64,
                 from /usr/include/c++/8/vector:60,
                 from Serial2Mqtt.h:10,
                 from Serial2Mqtt.cpp:2:
/usr/include/c++/8/bits/stl_pair.h: In instantiation of ‘struct std::pair<const std::__cxx11::basic_string<char>, Bytes>’:
Serial2Mqtt.cpp:615:124:   required from here
/usr/include/c++/8/bits/stl_pair.h:303:17: error: ‘constexpr std::pair<_T1, _T2>::pair(const std::pair<_T1, _T2>&) [with _T1 = const std::__cxx11::basic_string<char>; _T2 = Bytes]’ declared to take const reference, but implicit declaration would take non-const
       constexpr pair(const pair&) = default;
                 ^~~~
make: *** [serial2mqtt.mk:102: Debug/Serial2Mqtt.cpp.o] Error 1

```

**Comment by vortex314** [comment]
Compiler raspberry pi
lieven@pi30:~/workspace/serial2mqtt $ g++ --version
```
g++ (Raspbian 8.3.0-6+rpi1) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Compiler PC ( no issue )
```
lieven@pcdell:~/workspace/serial2mqtt$ g++ --version
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by PizzaProgram** [comment]
> /ArduinoJson/ ...

There are at least 4 common libraries for that.
In the example files for Arduino you are including Arduino_JSON, now I see the other.
Which one is the right one?
 - is it possible you are using 2 different types of this library for Arduino and for the gateway?

![kép](https://user-images.githubusercontent.com/26026089/103420306-d70c0980-4b96-11eb-8dc6-907bf6e5b948.png)

**Comment by vortex314** [comment]
Your question is not related to the issue at hand. 
I don't use Arduino IDE. 
I just clone bblanchon/ArduinoJson

**Comment by vortex314** [comment]
@halfbakery  I had to comment some lines out, as they didn't compile on a raspberry pi. Can you have a look ? 
```
	for (map<string, Bytes>::iterator lpmi = _mqttLocalPersistenceMessages.begin(); lpmi != _mqttLocalPersistenceMessages.end(); ++lpmi)
	{
		serialPublish(PUBLISH, lpmi->first, lpmi->second, 0, true);
	}
```
Thanks.

**Comment by PizzaProgram** [comment]
> Your question is not related to the issue at hand.

Sorry and Thank you!
 That means I've picked the wrong lib...
bblanchon is the 2th one. I've installed the 1th.
...anyway it seems you did not upgrade from version 5 to version 6...
```
  static void handleLine(String& line) {
    StaticJsonBuffer<200> jsonBuffer;
```

Error: 
```
StaticJsonBuffer is a class from ArduinoJson 5.`  
Please see arduinojson.org/upgrade to learn how to upgrade your program to ArduinoJson version 6
```
After fix:
```
  static void handleLine(String& line) {
    StaticJsonDocument<200> jsonBuffer;
    deserializeJson(root, line);
...
```

**Comment by PizzaProgram** [comment]
> I don't use Arduino IDE.
What dev. env. are you using? How else do you upload your code to an Arduino?

**Comment by vortex314** [comment]
https://platformio.org/install/ide?install=vscode
Or just VSCode

**Comment by halfbakery** [comment]
> @halfbakery I had to comment some lines out, as they didn't compile on a raspberry pi. I cannot figure out why it fails, plenty of articles on the internet on this. The code should work , but with this version of compiler it fails.
> 
> Can you have a look ?
> 
> ```
> 	for (map<string, Bytes>::iterator lpmi = _mqttLocalPersistenceMessages.begin(); lpmi != _mqttLocalPersistenceMessages.end(); ++lpmi)
> 	{
> 		serialPublish(PUBLISH, lpmi->first, lpmi->second, 0, true);
> 	}
> ```
> 
> Thanks.

I'll look into this.

**Comment by halfbakery** [comment]
Here's the fix for the map<string, Bytes> problem, please apply to the Common library:
```
diff --git a/Bytes.cpp b/Bytes.cpp
index 9a0f01e..7b1cb02 100644
--- a/Bytes.cpp
+++ b/Bytes.cpp
@@ -70,7 +70,7 @@ Bytes::~Bytes() {
         if (_start)
             free(_start);
 }
-Bytes::Bytes(Bytes& src) {
+Bytes::Bytes(const Bytes& src) {
     _start = (uint8_t*)malloc(src._capacity);
     _offset = 0;
     _limit = src._limit;
diff --git a/Bytes.h b/Bytes.h
index 8a3b2c8..12e707b 100644
--- a/Bytes.h
+++ b/Bytes.h
@@ -25,7 +25,7 @@ class Bytes {
     Bytes(uint32_t size);
     Bytes(uint8_t* start, uint32_t size);
     Bytes& map(uint8_t* start, uint32_t size);
-    Bytes(Bytes& in);
+    Bytes(const Bytes& in);
     ~Bytes();
     Bytes& clone(Bytes& src);
     //    void map(uint8_t *start, uint32_t size);
```

**Comment by vortex314** [comment]
@halfbakery  thanks ! I will merge and test it.

**Comment by vortex314** [comment]
Compilation on raspberry pi showed successful. Thanks ! 
I removed the #ifndef for __arm__
