### ISSUE TITLE
Insufficient config buffer size

### ISSUE THREAD

**Issue by halfbakery** [vortex314/serial2mqtt#26]
Maybe it's better fitted to the Common repository, but it has effects only in serial2mqtt.

In the Common/Config.cpp:
```
Config::Config()
       : _jsonBuffer(1024)
```
which is too small, larger serial2mqtt configs couldn't be loaded (it happened to me). Please increase this limit somehow.

**Comment by vortex314** [comment]
I will take care, I'm just used to sizing at micro-controller side , so 1KB RAM is a lot, but it's peanuts at linux side.

**Comment by halfbakery** [comment]
Yeah, that was my idea too :-)

My initial guess was adding an argument to the constructor to set the size of the buffer, but I've seen its a global variable defined in Config/Config.cpp. So it was easier to file an issue than sending a PR :-)
