### ISSUE TITLE
Errors launching pre-build versions from the Debug directory

### ISSUE THREAD

**Issue by BOSS-CC** [vortex314/serial2mqtt#31]
Attempting to work with the pre-builds of serial2mqtt I get the following error:

```
serial2mqtt/build/Debug $ ./serial2mqtt.armv6l 
./serial2mqtt.armv6l: /lib/arm-linux-gnueabihf/libc.so.6: version GLIBC_2.28 not found (required by ./serial2mqtt.armv6l)
```

Tried both armv6l and armv7l pre-builds and received the same error message on my RPi.
Figured this maybe libc6 needing updating, so:

```
serial2mqtt/build/Debug $ sudo apt-get install libc6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libc6 is already the newest version (2.24-11+deb9u4).
```

Uh oh. Does this require using a newer libc6 version not supported by the Raspbian distro?

**Comment by vortex314** [comment]
Which raspbian version are you running ? 
As this code was compiled on the latest version of raspbian.

**Comment by BOSS-CC** [comment]
Yep that's a good question.

I had `sudo apt-get upgrade` to the most recent that was able to achieve, but no luck.

Then I got brave and a little crazy and tried adding debian sid to /etc/apt/sources.list and comprehensively destroyed the entire system so I'm about to try again from a freshly created SD image.

**Comment by BOSS-CC** [comment]
OK Yep this issue is resolved by using the latest version of Raspbian, thanks.

I would expect issue #30 is also related to using an old Raspbian version, I'll check that shortly.

**Comment by BOSS-CC** [comment]
Lieven is there a way I can contact you to discuss my application using your serial2mqtt work?

**Comment by vortex314** [comment]
Via Google Hangouts ?

**Comment by BOSS-CC** [comment]
I haven't used that before, but I could figure it out.

Email me and we'll arrange something? I'm UTC+8 Western Australia time.
chris at switchbatteries dot com

Thanks mate
