### ISSUE TITLE
Starting a serial2mqtt service - ignoring serial2mqtt.json configuration

### ISSUE THREAD

**Issue by SimonMerrett** [vortex314/serial2mqtt#43]
Hi @vortex314 thanks again for this project - I have returned to my use of this and from reading your mqtt2serial I can also (without directly employing mqtt2serial) enjoy the keep-alive sub/pub approach you use there to help with connection maintenance. 

I am trying to run serial2mqtt as a service, along the same lines at the zigbee2mqtt service I am also running on the pi (zero - using the armv6 build you kindly provided).

I have run into problems where when I run serial2mqtt from an SSH command line into the pi, it correctly uses my local mqtt broker running on the pi and opens the correct Serial0 connection, as per my seral2mqtt.json configuration file. However, when I run serial2mqtt as a service, it is clearly using default values and ignoring my json config file:
![image](https://user-images.githubusercontent.com/26767525/124475405-95ecf000-dd99-11eb-8261-586684c3b43f.png)
![image](https://user-images.githubusercontent.com/26767525/124475453-a43b0c00-dd99-11eb-84e4-ec821d6a2f6f.png)
This is how I have been setting up the service:
`sudo nano /etc/systemd/system/serial2mqtt.service
`
```
[Unit]
Description=serial2mqtt
After=network.target

[Service]
ExecStart=/home/pi/serial2mqtt
WorkingDirectory=/home/pi/
StandardOutput=inherit
StandardError=inherit
Restart=always
User=pi

[Install]
WantedBy=multi-user.target
```
I have tried it with and without the working directory. I know in #2 you said you hadn't tried running it as a service but if you have any clue why the config file is being ignored, please could you share them with me? Thank you.

**Comment by SimonMerrett** [comment]
Hmm. A reboot on the pi means the instance of serial2mqtt run by the service seems to have now accepted the config file settings and things _seem_ to be playing nicely together. @vortex314 would you like me to close this now and reopen if I come up against more issues? Or would it be OK to leave it open while I do a little more testing?

**Comment by SimonMerrett** [comment]
There seems to be some log file permission access issues. I shall try to brush up on my knowledge of linux permissions but if what I have done is obviously wrong and you can tell me, please say:
![image](https://user-images.githubusercontent.com/26767525/124479532-49f07a00-dd9e-11eb-9284-e14f9f6f95a9.png)
My serial2mqtt.json settings are:
```
{
    "mqtt": {
        "connection": "tcp://localhost:1883"
    },
    "serial": {
        "baudrate": 115200,
        "ports": [
            "/dev/serial0"
        ],
        "protocol": "jsonArray"
    },
    "log": {
        "protocol": true,
        "debug": true,
        "useColors": true,
        "mqtt": false,
        "program": false,
        "level": "I",
        "file": "log.serial2mqtt.",
        "console": true
    }
}
```

**Comment by SimonMerrett** [comment]
I now think that my pre-existing log files were write protected because I was silly and used
`sudo ./serial2mqtt`
as my command to get the app running. Then when I switched over to a service, the pi user didn't have super user rights, so couldn't write to the files that had previously been written by a super user process. 
I deleted all the log files, started again and don't get any complaints about log file permission denied. The logging stream from 
` sudo journalctl -u serial2mqtt.service -f`
is still a bit sporadic. Nothing comes in until a large jsonArray arrives (my keepalive publishing doesn't trigger a new line) and then a large multi-line update happens.

Closing now but if you have any observations, @vortex314, I would be very glad to hear them. Thanks again for this project.

**Comment by SimonMerrett** [comment]
For reference, my current systemd service reference is 
```
[Unit]
Description=serial2mqtt
After=network.target

[Service]
ExecStart=/home/pi/serial2mqtt
WorkingDirectory=/home/pi
Restart=always

[Install]
WantedBy=multi-user.target

```

**Comment by vortex314** [comment]
Hi Simon, glad to see you solved everything yourself by the time I detected there was an issue. :-)
Feel free to contact me if any other issue arises.
Success !
Lieven
