### ISSUE TITLE
How to use SSL/TLS connection

### ISSUE THREAD

**Issue by RadioOperator** [vortex314/serial2mqtt#44]
Hi All, I tried to mod this code for a SSL/TLS connections, 

set `PAHO_WITH_SSL ` to `TRUE`,
set `conn_opts.ssl....` parameters in mqttconnect() function, 

Compiling is passed, but connection not work and halt/exit, the code seems not properly install `openssl lib`, because the code size not changed than no-SSL code.

I cannot find any reference on this, Anyone could help me, thanks.

**Comment by RadioOperator** [comment]
fixed myself, many mods, still under testing.

**Comment by vortex314** [comment]
@RadioOperator  could you share your finds or code ? Wil help others.

**Comment by RadioOperator** [comment]
@vortex314 It's OK, let me doing more testings (~1 month) and report you, thanks.

**Comment by RadioOperator** [comment]
@vortex314  Hi, after several days running, paho.mqtt.c for SSL/TLS is robust, but its makefiles not ready to use, also maybe I'm doing something wrong. In your code, my mods:

1. install openssl libaray, in file build.sh
    should add "git clone openssl..." source code to build out libssl.so file
    I do not know how to link to ubuntu libssl-dev.

2. in file makePaho.sh
    ${CC:-cc}...   add   src/SSLSocket.c
    ${AR:-ar}...   add   SSLSocket.c   and   {absoluted openssl build output path}/openssl.so

3. in files, serial2mqtt.mk and serial2mqtt.project:
    libpaho-mqtt3c.a    to   libpaho-mqtt3cs.a

4. file Cmakefile.txt in /pahp.mqtt.c/src/ folder:
    add SSLSocket.c filename in common_src list

5. Cmakefile.txt in /paho.mqtt.c/ folder:
    line:  SET(PAHO_WITH_SSL FALSE........
    mod to: SET(PAHO_WITH_SSL TRUE........, but no effects for "#if defined(OPENSSL)", still get non-SSL!

6. to force enable SSL code, add followings to all source files using #if defined(OPENSSL):

    #if !defined(OPENSSL)
        #define OPENSSL 1
    #endif

7. app SSL/TLS connection releted, refer to: https://forums.aws.amazon.com/thread.jspa?threadID=345250

That's all. Just for your reference, sorry, the complete code cannot share.
I hope if you have time, make your code a simple option switch in bash/makefiles to enable SSL/TLS connection.
(Not tested, if this mods could be back compatible with non-SSL connection.)
