### ISSUE TITLE
Connecting on Marantz Sr6004 

### ISSUE THREAD

**Issue by mitro72** [vortex314/serial2mqtt#45]
I've an Homeassistant installation (minipc) connected on serial to Marantz Sr6004, my serialport configuration on config.yaml of 2mqtt is:

adapters:
  - name: adapter1
    enabled: true
    reconnect_delay: 20s
    provider: raw
    source:
      type: serial
      port: /dev/ttyS1
      baud_rate: 9600
      transmit_pre_delay: 10ms
    mqtt:
      broker: tcp://xxx.xxx.xxx.xxx:1883
      insecure_skip_verify: false
      username: xxxx
      password: xxxx
      subscribe: in_marantz/#
      publish: out_marantz
      qos: 0
      transmit_pre_delay: 100ms
      reconnect_delay: 5s

In accorting to Marantz documentation if I send a command (ES: @PWR:1\r)  on in_marantz topic, the device succesfully power ON itself, but if I send a STATUS command (ES: @PWR:?\r), in terminal windows the device respond correctly it's STATE (@PWR:1 in case of ON and @PWR2 in case of OFF)  but with  serial2mqtt it is unable to fetch this values  and send message on out_marantz topic.

wath I can do?
Tnx

**Comment by vortex314** [comment]
@mitro72  not sure what your setup is. If I understand correctly , you're trying to connect to connect a Marantz SR6004 https://www.marantz.com/en-us/product/av-receivers/sr6004 via serial port to a minipc. 
The marantz is unlikely to talk the protocol that is needed for the serial2mqtt communication. Based on the examples given, it looks like a simple line based ( cr lf ) protocol, which is not JSON object based ( on what serial2mqtt ) expects. Serial2mqtt is intended for communication with a device that is capable of being programmed to understand the same protocol. 
In your case I would write a MQTT listener that triggers these line based commands to the marantz via the serial port.
Hope this helps.

**Comment by mitro72** [comment]
Yes! you are right!! Marantz is line based, if you could many thanks!!! I think this can help to integrate many older devices...
Great!! 
Whish best!!

**Comment by vortex314** [comment]
@mitro72  just to be clear, I was just suggesting a path of solution, myself have no plans to develop this. As also I have no use case or device to test against. Sorry if there was some misunderstanding.

**Comment by mitro72** [comment]
ok! no problem!

**Comment by vortex314** [comment]
not fit for purpose.
