### ISSUE TITLE
Serial String

### ISSUE THREAD

**Issue by Christoph1111** [vortex314/serial2mqtt#46]
`Serial.println("[1,\"src/myTopic/time\","+String(millis())+"]");`
What does the first Number (1) mean?

**Comment by vortex314** [comment]
The number is a short-hand notation of the command . Here it means : PUBLISH
	typedef enum
	{
		SUBSCRIBE = 0,
		PUBLISH,
		CONNECT,
		DISCONNECT
	} CMD;

**Comment by vortex314** [comment]
Considered answered.
