### ISSUE TITLE
wget directions returns 404 Not Found

### ISSUE THREAD

**Issue by TGit-Tech** [vortex314/serial2mqtt#48]
In the readme the installation for build versions shows

wget https://github.com/vortex314/serial2mqtt/raw/master/Debug/serial2mqtt.`arch`.zip

I got a 404 Not Found.
Then changed it to https://github.com/vortex314/serial2mqtt/raw/master/build/serial2mqtt.`arch`.zip
and it works.  Think your Readme needs updated.

**Comment by vortex314** [comment]
no more builds, please rebuild on target platform with cmake
