### ISSUE TITLE
Why are there two README files?

### ISSUE THREAD

**Issue by ondras12345** [vortex314/serial2mqtt#50]
There is [`README.md`](https://github.com/vortex314/serial2mqtt/blob/3c48274b948a7546bf3ee791d2f72c2a473fe10f/README.md) and [`docs/README.md`](https://github.com/vortex314/serial2mqtt/blob/3c48274b948a7546bf3ee791d2f72c2a473fe10f/docs/README.md), the latter of which was last updated 5 years ago and contains outdated information about the communication protocol.
What is the purpose of the second file?

**Comment by vortex314** [comment]
cleaned
