### ISSUE TITLE
Don't store compiled binaries in Git repository

### ISSUE THREAD

**Issue by ondras12345** [vortex314/serial2mqtt#52]
I would like to suggest to distribute build outputs via [Github releases](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases) instead of putting them in the Git repository ([`build/` directory](https://github.com/vortex314/serial2mqtt/tree/3c48274b948a7546bf3ee791d2f72c2a473fe10f/build)). Git cannot diff binary files effectively, resulting in a very large repository (it contains not only the current version of those binary files, but also all previous versions). It takes quite a long time to clone this repository.

**Comment by vortex314** [comment]
no builds anymore, however no time to spend on github releases. Feel free .
