### ISSUE TITLE
MQTT Serial in device Arduino R3+esp8266+ch340g

### ISSUE THREAD

**Issue by Vicente-Ch** [vortex314/serial2mqtt#54]
English:
 Hello, how are you.  I have the board "Arduino R3+esp8266+ch340g"
 https://a.aliexpress.com/_EIljyH9

 On the Arduino I have a lawnmower robot project which I want to communicate with "Home Assistant".  I already have the esp8266 connected to the Home Assistant Mqtt broker via Wi-Fi.  Using the following library:
 https://www.arduino.cc/reference/en/libraries/home-assistant-integration/

 I only need to pass the messages through the serial port (tx/rx) that unites the two microprocessors on the same board.  It should be a two-way communication to, in addition to receiving information on the status of the robot, be able to send commands to start, stop, return home.
 I don't know how to implement your library.  Could you give an example of the codes that must be loaded into each of the processors, atmega328 and esp8266.
 Thank you very much in advance
-----------------------------------+++----------------------------
Español:
Hola, q tal. Tengo la placa "Arduino R3+esp8266+ch340g"
https://a.aliexpress.com/_EIljyH9

En el Arduino tengo un proyecto de robot cortacesped el cual quiero comunicar con "Home Assistant". El esp8266 ya lo tengo conectado al broker Mqtt de Home Assistant via wifi. Usando la siguiente libreria:
https://www.arduino.cc/reference/en/libraries/home-assistant-integration/

Solo me falta pasar los mensajes por el puerto serie (tx/rx) q une los dos microprocesadores en la misma placa. Deberia ser una comunicacion bidireccional para, ademas de recibir informacion del estado del robot poder mandarle comandos de marcha, paro, volver a casa.
No se como implementar tu libreria. Podrias poner un ejemplo de los codigos q hay q cargar en cada uno de los procesadores, atmega328 y esp8266.
Muchas gracias de antemano

**Comment by vortex314** [comment]
The serial2mqtt program is made to run on a linux platform like a PC or a raspberry Pi. It uses linux system calls and libraries.
What you need is a serial-to-mqtt running on the ESP8266, the ESP8266 doesn't support the linux platform.
What you could do write code on the ESP8266 that :
- reads messages from the UART coming from the ATMEGA
- translate them to MQTT requests send over the Wifi of the ESP8266. 
- Get publish messages from the Wifi on ESP8266 and send them over serial to the ATMEGA
- for the serial communication you could use the same protocol as I do in serial2mqtt and use ArduinoJson with a PPP envelope to assure integrity of the communication.
Hope this helps.

**Comment by vortex314** [comment]
As the requirements of this software don't match your available platform, it cannot be solved.
