### ISSUE TITLE
Missing license on this project

### ISSUE THREAD

**Issue by twoellert** [vortex314/serial2mqtt#59]
Hey!

Is it possible to select a license for this project? Becaue if no license is selected - even though its published on github - means that basically the code is all rights reserved and not really usable for open source. Which I think was not the intention ;)

Thanks!

Tom

**Comment by vortex314** [comment]
Any preferred license form ?

**Comment by twoellert** [comment]
Good question ;)

The most simple one is the MIT license, if you want to keep it completely open to everything:
https://choosealicense.com/licenses/mit/

Alternative is the more complex GPLv3 which has a few restrictions compared to MIT:
https://choosealicense.com/licenses/gpl-3.0/

Up to you, since you invested the time and energy to create that nice piece of software. Thanks for that by the way :)

Tom

**Comment by vortex314** [comment]
added MIT license file
