### ISSUE TITLE
Home Assistant Addon?

### ISSUE THREAD

**Issue by falkn** [vortex314/serial2mqtt#6]
Hi Lieven!

This library looks exactly like what I need, I have some sensors and actuators driven by an arduino. The Arduino is connected through serial to a Raspberry Pi. My Raspberry Pi runs Home Assistant and Hass.io (https://www.home-assistant.io/hassio/), which means it has neat handling for addons that runs as a docker container.

Have you had any thoughts to make this a docker container or even a home assistant addon? This would basically mean to make the builds reproducible and skip the list of instructions on what needs to be installed to build it, for example by using http://bazel.build/

Kindest,
Christian

**Comment by vortex314** [comment]
Hi Christian,
thanks for the positive feedback. I will certainly give it some thoughts to make it a docker container. 
If you are just interested in running the software, just unzip the build in the build subdirectory. It's staticly linked ( just one executable ) and requires a json config on which you can find a sample in the root directory.
As I am myself not using home-assistant, though the product looks interesting, I will not directly spend time on this. Thanks anyway it looks promising for a future project.. My ambitions are oriented differently : https://vortex314.blogspot.com/

Regards
Lieven

**Comment by vortex314** [comment]
I guess the response closes the issue, let me know otherwise.

**Comment by falkn** [comment]
Yes! Thanks for the response! Sounds like nice ambitions as well :)
