### ISSUE TITLE
Saying Hello

### ISSUE THREAD

**Issue by banier1** [vortex314/serial2mqtt#7]
Hi Lieven,
I'm very interested in finding a solution, to an issue, that I think this Git provides.
I am setting up a home automation system using a raspberry pi loaded with OpenHAB (which has an embedded mqtt broker)  and an Arduino Mega and an Arduino Uno for handling the I/0 (I have 86 I/O!!!) 44 inputs and 42 outputs.  The Raspberry pi and Arduinos are located next to one another in my main cupboard, with all input and output cables being lead back to cupboard during a recent rewiring of my house.
I also would like to use MQTT, as I have some wireless devices too and would like a universal communications format.
Therefore I very keen to communicate between Raspberry Pi and Arduinos using USB link, communicating using MQTT.  Your Git seems to have the solution I'm looking for....however the problem is i'm not experienced in using Github or understanding/writing code.
Could you help provide step-by-step guide or instruction of how I could use your solution?
Any help would be gratefully appreciated.
Many Thanks Dan

**Comment by vortex314** [comment]
Hi Dan,
Thanks for your interest. 
the easiest start is : 

-  download : https://github.com/vortex314/serial2mqtt/raw/master/build/serial2mqtt.armv7l.zip
-  unzip it on your raspberry pi.
-  You have to add a config file in the same directory where you unzipped the above. 
-  A sample config : https://github.com/vortex314/serial2mqtt/raw/master/serial2mqtt.json

When you run the above serial2mqtt it should use the config file and try to find the expected protocol on some USB ports : /dev/ttyUSB0. You can add more in the config file .

For the complete setup see  this documentation page with some Arduino samples : https://github.com/vortex314/mqtt2serial/blob/master/README.md
This should get you started to load the code and run.

Let me know if you have more specific questions.
Lieven

**Comment by banier1** [comment]
Wow, thank you Lieven, for your prompt and informative reply.
I will try it tomorrow.  I've not unzipped to my Pi before, so there's a lot of learning for me.
I hope my mqtt broker can connect with it's clients through USB when this is done.  It would be magnificent.
Maybe I could get your opinion?...It seems like this is not a well known solution for a problem that i would thought is common.  How many people have used your solution?
Kind Regards, Dan

**Comment by banier1** [comment]
Also could you recommend a suitable location (directory) on my Pi where I should UNZIP?
And do you know the suitable command for downloading and unzipping?

Many thanks

**Comment by vortex314** [comment]
Dan, 
no idea how many users use it.
Unzip : https://linux.die.net/man/1/unzip
Download : https://linuxize.com/post/curl-command-examples/
Good luck,
Lieven

**Comment by banier1** [comment]
Lieven,

My first attempt at downloading from your link didn't go well.  See attached screenshot.
The command I used was :
sudo curl -sL https://github.com/vortex314/serial2mqtt/raw/master/build/serial2mqtt.armv7l.zip   
Please help.
Many Thanks, Dan

![Screen Shot 2020-06-04 at 19 42 16](https://user-images.githubusercontent.com/66334240/83798119-a82ec300-a69b-11ea-83c0-4c591b7b2f6d.png)

**Comment by banier1** [comment]
Further the to the above, I've now managed to download the serial2mqtt.armv7l.zip file.
Now I'm unable to unzip it, despite the instructions on the webpage on the link you kindly sent.
I get the following message:

End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of serial2mqtt.armv7l or
        serial2mqtt.armv7l.zip, and cannot find serial2mqtt.armv7l.ZIP, period.

**Comment by vortex314** [comment]
This sequence should work 
**$ curl -O https://raw.githubusercontent.com/vortex314/serial2mqtt/master/build/serial2mqtt.armv7l.zip**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  572k  100  572k    0     0   346k      0  0:00:01  0:00:01 --:--:--  346k
**$ unzip serial2mqtt.armv7l.zip**
Archive:  serial2mqtt.armv7l.zip
  inflating: Debug/serial2mqtt.armv7l  
**$ cd Debug**
**$ curl -O https://raw.githubusercontent.com/vortex314/serial2mqtt/master/serial2mqtt.json**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   200  100   200    0     0   1360      0 --:--:-- --:--:-- --:--:--  1351
**$ ./serial2mqtt.armv7l**
serial2mqt I | 21:35:12.763  | pi3 |        main.cpp:  42 | build : Dec 15 2019 13:46:30
serial2mqt I | 21:35:12.763  | pi3 |        main.cpp:  43 |  argv[0] : ./serial2mqtt.armv7l 
serial2mqt I | 21:35:12.764  | pi3 |      Config.cpp: 248 |  config loaded : {"mqtt":{"connection":"tcp://test.mosquitto.org:1883"},"serial":{"baudrate":115200,"ports":["/dev/ttyUSB0"],"protocol":"jsonArray"}}
serial2mqt I | 21:35:12.764  | pi3 |        main.cpp:  69 |  configuring port : /dev/ttyUSB0
serial2mqt I | 21:35:12.765  | pi3 |        main.cpp:  78 |  starting thread 0
      USB0 I | 21:35:12.765  | pi3 | Serial2Mqtt.cpp: 574 |  MQTT connecting tcp://test.mosquitto.org:1883 ... for USB0 
      USB0 I | 21:35:12.765  | pi3 | Serial2Mqtt.cpp: 560 |  MQTT connection state MS_DISCONNECTED => MS_CONNECTING 
      USB0 I | 21:35:12.765  | pi3 | Serial2Mqtt.cpp: 560 |  MQTT connection state MS_CONNECTING => MS_CONNECTING 
      USB0 I | 21:35:12.766  | pi3 | Serial2Mqtt.cpp: 291 | Connecting to '/dev/ttyUSB0' ....
      USB0 E | 21:35:12.766  | pi3 | Serial2Mqtt.cpp: 295 | connect: Unable to open '/dev/ttyUSB0' errno : 2 : No such file or directory 
      USB0 I | 21:35:13.077  | pi3 | Serial2Mqtt.cpp: 560 |  MQTT connection state MS_CONNECTING => MS_CONNECTED 
      USB0 I | 21:35:13.077  | pi3 | Serial2Mqtt.cpp: 173 | MQTT_CONNECT_SUCCESS USB0 
      USB0 I | 21:35:13.077  | pi3 | Serial2Mqtt.cpp: 560 |  MQTT connection state MS_CONNECTED => MS_CONNECTED 
      USB0 I | 21:35:13.077  | pi3 | Serial2Mqtt.cpp: 616 | Subscribing to topic dst/pi3.USB0/# for client pi3.USB010033 using QoS0
      USB0 I | 21:35:13.078  | pi3 | Serial2Mqtt.cpp: 626 |  subscribe send 
      USB0 I | 21:35:13.109  | pi3 | Serial2Mqtt.cpp: 189 | MQTT_SUBSCRIBE_SUCCESS USB0

**Comment by banier1** [comment]
So I notice a different link in your most recent reply : 
https://raw.githubusercontent.com/vortex314/serial2mqtt/master/build/serial2mqtt.armv7l.zip

Whereas previously, in your first message, the link was : 
https://github.com/vortex314/serial2mqtt/raw/master/build/serial2mqtt.armv7l.zip

Would this be a different file?
If not, then I'm still having trouble unzipping the file on my Pi.  Note the "End-of-central-directory signature not found....." error message in my previous reply.

**Comment by vortex314** [comment]
the second link sends you through a redirect in the browser, something curl cannot handle 
I'm guessing you took the second link and you have a small file of about 157 bytes on your directory, which is not a zip file but a redirect. Take the first link.. 
Just execute these 5 commands and it should run.

**Comment by banier1** [comment]
Thank you for your help.
I have managed to unpack and complete the "curl -O https://raw.githubusercontent.com/vortex314/serial2mqtt/master/serial2mqtt.json".

However, when I typed " ./serial2mqtt.armv7l ", I got the following message:
" ./serial2mqtt.armv7l: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by ./serial2mqtt.armv7l) "

**Comment by vortex314** [comment]
looks like you need to install libc
```
sudo apt-get install libc6
```

**Comment by banier1** [comment]
![Screen Shot 2020-06-04 at 23 20 26](https://user-images.githubusercontent.com/66334240/83816326-0ff40680-a6ba-11ea-83bd-5af51581aabe.png)

Not worked.  Seems like I already have the latest version installed, going by the response.

One thing to note is I am already using 2x of the USB ports on my Pi.  These are required for a flash drive used for boot and a CC2531 required for zigbee2mqtt.  Would the fact that these are already connected to USB cause a problem?

**Comment by vortex314** [comment]
Using other systems connected on USB shouldn't pose a problem. Except if they allocate a port like /dev/ttyUSBx which is configured in the serial2mqtt.json file.
The GLIC issue is linked to a different version of LIBC on your system and mine. 
See also : https://github.com/gotify/server/issues/225
You can check the version with :```
ldd --version
```

**Comment by banier1** [comment]
Hi Lieven,

Thank you for your reply.
For the port, I followed [zigbee2mqtt.io](https://www.zigbee2mqtt.io/getting_started/running_zigbee2mqtt.html) installation.  In there, it asks to check the location of CC2531 sniffer is /dev/ttyACM0.

I also previously found the link you sent, but being honest with you, I couldn't follow it, in understanding what to do. Would you be so kind to let me know how to update the GLIC?

I executed the version checking command.  (Result below)
I seem to have 2.24, where you have 2.28.
Is there a simple way to upgrade?
`[14:45:33] openhabian@openHABianPi:~$ ldd --version
ldd (Debian GLIBC 2.24-11+deb9u4) 2.24
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.`

Many Thanks, Dan

**Comment by vortex314** [comment]
The easiest way to update : 
```
sudo apt-get update
```
check the version again with the ldd command. If not correct yet then do : 
```
sudo apt-get upgrade
```

**Comment by banier1** [comment]
Hi again,

Isn't that the command to complete a whole system update?  If so, is that right?
Just checking... as I completed an update (of OpenHabian) just a couple of weeks ago.
Please confirm.

Regards,
Dan

**Comment by vortex314** [comment]
Looks that OpenHabian is still based on an older version of Raspian. According to this [page](https://www.openhab.org/docs/installation/rasppi.html) you can install raspian and openhab serparately , but I guess this is leading you too far in a complex installation.

**Comment by banier1** [comment]
It does sound complicated.  Too complicated for me.
So I guess I'm stuck - if OpenHabian contains an old version of GLIC, which can't be updated unless the administrators of OpenHabian provide an update.
Am I right?

**Comment by vortex314** [comment]
The other options would be :  

1. Build directly on your raspberry pi following the build instructions : https://github.com/vortex314/serial2mqtt#build-instructions
2. Run docker on your raspi  and I could provide a docker image : https://phoenixnap.com/kb/docker-on-raspberry-pi

**Comment by banier1** [comment]
Hi Lieven,

Thank you for your suggestions.
Could you provide an explanation of each option, with possible advantages of each compared with the other?
1. If I build on the raspberry pi that OpenHabian is running, is there suitable interaction between the OpenHabian and the build, so the operation is appropriate?  
On the link you sent, is the build process, just the 8 steps quoted ? I don't understand what us required for the steps.
2.  I'm not clear on how containers work.  Is it that OpenHabian is in a container and serial2mqtt is in another container?  Do I require to remove openhabian as an OS and then install docker where then openhabian in installed in one container; serial2mqtt in another?

Apologies that you dealing with a numpty like me,
Thank you for all your help.  I am keen to use your solution, to save me network connecting my 2x Arduinos.

Kind Regards, Dan

**Comment by banier1** [comment]
Also, is it worth questioning the OpenHAB developers, via their forum, about the  possibility to upgrade OpenHabian to have the latest version of GLIC?

**Comment by vortex314** [comment]
Hi Dan,

the script is basicly doing all steps, long time I didn't verify if it works, but you could give it a try : https://github.com/vortex314/serial2mqtt/blob/master/build.sh
it supposes that you have C++ development tools installed , this is normally the case for Raspian n Don't know for OpenHab.
Seen your questions, I think docker container is a step too far.
You can certainly check with OpenHab developers when their update of GLIBC to 2.28 will be done.

Lieven

**Comment by banier1** [comment]
Hi Lieven,

I put the following post on the OpenHAB forum > [https://community.openhab.org/t/glibc-update-on-openhabian/100273](https://community.openhab.org/t/glibc-update-on-openhabian/100273)

They are suggesting a complete reinstall of the OpenHABian OS image onto my Pi., which I have been through before with the original install, so I might give that a go.

Any thoughts?
Thanks for your help.  I'll be back in contact when I've reinstalled and ready for serial2mqtt install again....
Regards,Dn

**Comment by vortex314** [comment]
Hi Dan,
looks they also suggest to do an upgrade : 
```
# apt-get update
# apt-get upgrade
# apt-get dist-upgrade
````
Looks easier than a full install, could give it a try.
Lieven

**Comment by banier1** [comment]
I believe I've done it... the upgrade, that is.
I then completed the  last command you steps, i.e. **$ ./serial2mqtt.armv7l**
Results are below.
Noticing that it is not finding "ttyUSB0" in dev folder.
Would that be because I don't current;y have another device connected to the USB port, or is it that the directory name that is looking for does not exist, and it shoudl be looking for another name?

`serial2mqt I | 10:57:14.959  | openHABianPi |        main.cpp:  42 | build : Dec 15 2019 13:46:30
serial2mqt I | 10:57:14.960  | openHABianPi |        main.cpp:  43 |  argv[0] : ./serial2mqtt.armv7l 
serial2mqt I | 10:57:14.965  | openHABianPi |      Config.cpp: 248 |  config loaded : {"mqtt":{"connection":"tcp://test.mosquitto.org:1883"},"serial":{"baudrate":115200,"ports":["/dev/ttyUSB0"],"protocol":"jsonArray"}}
serial2mqt I | 10:57:14.965  | openHABianPi |        main.cpp:  69 |  configuring port : /dev/ttyUSB0
serial2mqt I | 10:57:14.966  | openHABianPi |        main.cpp:  78 |  starting thread 0
      USB0 I | 10:57:14.966  | openHABianPi | Serial2Mqtt.cpp: 574 |  MQTT connecting tcp://test.mosquitto.org:1883 ... for USB0 
      USB0 I | 10:57:14.966  | openHABianPi | Serial2Mqtt.cpp: 560 |  MQTT connection state MS_DISCONNECTED => MS_CONNECTING 
      USB0 I | 10:57:14.968  | openHABianPi | Serial2Mqtt.cpp: 560 |  MQTT connection state MS_CONNECTING => MS_CONNECTING 
      USB0 I | 10:57:14.968  | openHABianPi | Serial2Mqtt.cpp: 291 | Connecting to '/dev/ttyUSB0' ....
      USB0 E | 10:57:14.968  | openHABianPi | Serial2Mqtt.cpp: 295 | connect: Unable to open '/dev/ttyUSB0' errno : 2 : No such file or directory 
      USB0 I | 10:57:15.098  | openHABianPi | Serial2Mqtt.cpp: 560 |  MQTT connection state MS_CONNECTING => MS_CONNECTED 
      USB0 I | 10:57:15.098  | openHABianPi | Serial2Mqtt.cpp: 173 | MQTT_CONNECT_SUCCESS USB0 
      USB0 I | 10:57:15.098  | openHABianPi | Serial2Mqtt.cpp: 560 |  MQTT connection state MS_CONNECTED => MS_CONNECTED 
      USB0 I | 10:57:15.098  | openHABianPi | Serial2Mqtt.cpp: 616 | Subscribing to topic dst/openHABianPi.USB0/# for client openHABianPi.USB01577 using QoS0
      USB0 I | 10:57:15.098  | openHABianPi | Serial2Mqtt.cpp: 626 |  subscribe send 
      USB0 I | 10:57:15.126  | openHABianPi | Serial2Mqtt.cpp: 189 | MQTT_SUBSCRIBE_SUCCESS USB0 
      USB0 I | 10:57:20.535  | openHABianPi | Serial2Mqtt.cpp: 291 | Connecting to '/dev/ttyUSB0' ....
      USB0 E | 10:57:20.535  | openHABianPi | Serial2Mqtt.cpp: 295 | connect: Unable to open '/dev/ttyUSB0' errno : 2 : No such file or directory 
      USB0 I | 10:57:26.044  | openHABianPi | Serial2Mqtt.cpp: 291 | Connecting to '/dev/ttyUSB0' ....
      USB0 E | 10:57:26.044  | openHABianPi | Serial2Mqtt.cpp: 295 | connect: Unable to open '/dev/ttyUSB0' errno : 2 : No such file or directory 
      USB0 I | 10:57:31.554  | openHABianPi | Serial2Mqtt.cpp: 291 | Connecting to '/dev/ttyUSB0' ....
      USB0 E | 10:57:31.554  | openHABianPi | Serial2Mqtt.cpp: 295 | connect: Unable to open '/dev/ttyUSB0' errno : 2 : `

**Comment by vortex314** [comment]
Ok looks good. 
There is nothing on /dev/ttyUSB0, but it keeps trying until something appears.
If you connect the Arduino on USB , you see a new device ? Called /dev/ttyUSB0
```
dmesg
```
this command should show, as which device the Arduino appears.
serial2mqtt  successfully connected to MQTT internet server test.mosquitto.org 
and subscribed to dst/openHABianPi.USB0/#

**Comment by banier1** [comment]
Hi Lieven,

I connected an Arduino Mega to one USB and an Arduino Uno to the the other.
Nothing is called ttyUSB0 in dev directory.
In my dev subdirectory I have ttyACM0, ttyACM1, ttyACM2, ttyAMA0
I think this must be them.

When completing the dmesg command, I get a large response:
I've extracted (what I think) the key points below:
I just can't seen to associate the tty_nnn_ to the found USBs

.....
[    2.141747] usb 1-1.2: new full-speed USB device number 4 using dwc_otg
[    2.290749] usb 1-1.2: New USB device found, idVendor=0451, idProduct=16a8, bcdDevice= 0.09
[    2.296458] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.299477] usb 1-1.2: Product: TI CC2531 USB CDC
[    2.302496] usb 1-1.2: Manufacturer: Texas Instruments
[    2.305485] usb 1-1.2: SerialNumber: __0X00124B0019368B6C
[    2.401744] usb 1-1.4: new full-speed USB device number 5 using dwc_otg
[    2.545628] usb 1-1.4: New USB device found, idVendor=2341, idProduct=0042, bcdDevice= 0.01
[    2.551352] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=220
[    2.557114] usb 1-1.4: Manufacturer: tt (www.arduino.cc)
[    2.560142] usb 1-1.4: SerialNumber: 5583834303435161B100
[    2.661745] usb 1-1.5: new full-speed USB device number 6 using dwc_otg
[    2.805627] usb 1-1.5: New USB device found, idVendor=2341, idProduct=0043, bcdDevice= 0.01
[    2.811413] usb 1-1.5: New USB device strings: Mfr=1, Product=2, SerialNumber=220
[    2.817250] usb 1-1.5: Manufacturer: Arduino (www.arduino.cc)
[    2.820189] usb 1-1.5: SerialNumber: 557373134313518141B2
[    3.121745] usb 1-1.3: new high-speed USB device number 7 using dwc_otg
[    3.252285] usb 1-1.3: New USB device found, idVendor=0781, idProduct=5571, bcdDevice= 1.00
[    3.257850] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    3.260756] usb 1-1.3: Product: Cruzer Fit
[    3.263651] usb 1-1.3: Manufacturer: SanDisk
[    3.266510] usb 1-1.3: SerialNumber: 4C530001260611120284
[    3.269944] usb-storage 1-1.3:1.0: USB Mass Storage device detected
[    3.273440] scsi host0: usb-storage 1-1.3:1.0
[    4.312911] scsi 0:0:0:0: Direct-Access     SanDisk  Cruzer Fit       1.00 PQ: 0 ANSI: 6
[    4.319718] sd 0:0:0:0: [sda] 30842880 512-byte logical blocks: (15.8 GB/14.7 GiB)
[    4.326474] sd 0:0:0:0: [sda] Write Protect is off
[    4.329309] sd 0:0:0:0: [sda] Mode Sense: 43 00 00 00
[    4.329627] sd 0:0:0:0: [sda] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
.....
    9.608967] cdc_acm 1-1.2:1.0: ttyACM0: USB ACM device
[    9.632669] usbcore: registered new interface driver uas
[    9.633320] cdc_acm 1-1.4:1.0: ttyACM1: USB ACM device
[    9.635530] cdc_acm 1-1.5:1.0: ttyACM2: USB ACM device
[    9.636587] usbcore: registered new interface driver cdc_acm
[    9.636597] cdc_acm: USB Abstract Control Model driver for USB modems and ISDN adapters

**Comment by vortex314** [comment]
Dan,
indeed it can also be /dev/ttyACM* depending on the chip on USB. 
You'll have to adapt the serial2mqtt.json to specify the right port. You will notice it's an array in the config, so you can specify multiple. 
```
{
    "mqtt": {
        "connection": "tcp://test.mosquitto.org:1883"
    },
    "serial": {
        "baudrate": 115200,
        "ports": [
		"/dev/ttyACM0","/dev/ttyACM1","/dev/ttyACM2"
        ],
	"protocol":"jsonArray"
    }
}
```
If there is other traffic on these ports ,  the serial2mqtt will look at each line captured and if it's not a JSON object structure , it will just show it as output on the console.
You could check the output of dmesg, when you unplug / plug the Arduino board,so you know which port to specify.
Don't forget that your Arduino needs to run some code for publishing and subscribing data.
And baudrate should be correct, in the above example it is 115200. So code should start with  something like Serial.begin(115200).

Lieven

**Comment by vortex314** [comment]
Most simple example : https://github.com/vortex314/mqtt2serial/blob/master/simple/src/main.cpp

**Comment by banier1** [comment]
Dear Lieven,

I'd just like to say thank you for your help and advice during my set-up of serial2mqtt.  It is most appreciated.  It does feel like we're getting there, after our initial hiccups.
I really hope to get this fully working, as I'm really keen to continue to use mqtt throughout my home automation system and have all my control devices (Raspberry Pi & 2x Ardunios).  1x arduino mega will be handling the 42 relay outputs and the other the 24 inputs from switches around my house.
Anyway - thanks again.  I will look to work through the processes in setting up mqtt on my arduinos (broker is already running on my Pi).

Kind Regards,
Dan

**Comment by banier1** [comment]
Just not sure how to tell which 2 out of the 4 USB ports (ttyACM0, ttyACM1, ttyACM2, ttyAMA0) are the arduinos....

**Comment by vortex314** [comment]
Dan,
you're welcome, always happy to see somebody else is looking for the same kind of solutions.
The ttyACMx numbering is assigned in the order you plug in your devices. So it can be changing continuously. 
There is some way around this that your device becomes something like /dev/ttyArduino always, this is based on some more detailed info on the USB bus of your devices. 
See : https://stackoverflow.com/questions/24714241/ttyusb-numbers-are-changing-after-reboot
There are more articles around this, I didn't try them myself. 
The easy way to get started is like I said, plug/unplug the Arduino and see which /dev/ttyACMx it is assigned. If that works together with your code, then it is useful to make the name fixed.
I guess this answers most of your questions, so I would suggest to close this issue and open another one once you would have more questions.
Success !
Lieven

**Comment by vortex314** [comment]
Closing issue
